### ISSUE TITLE
Test works, but not in flows.

### ISSUE THREAD

**Issue by torrfura** [jordenc/email-sender#8]
Testing my settings works, and I get an email, but sending an email via a flow does not. The spinning arrow never completes.

**Comment by jordenc** [comment]
Did you save the settings?

**Comment by Rene62** [comment]
I have the same issue. I have saved the settings

**Comment by michelkamp** [comment]
Same here. But also the test (was working before good) is now resulting in a URL above the test button..... BTW running latest homey 2.x firmware

**Comment by jordenc** [comment]
@michelkamp What is the URL / notice you get when running the test? Are you running 2.0+? I just noticed that that shows some javascript code that isn't supposed to be there. Will have to provide an update soon.

@moment77 @Rene62 I just tested the app under 2.0 and was able to send successful without a problem. Are you experienced with running apps from the commandline? That is currently the only way you can see the status of sending. After running the send command you should see something like this:
Message sent: 250 2.0.0 Ok: queued as 041C535F4308A

**Comment by michelkamp** [comment]
running latest v2 beta firmware

**Comment by michelkamp** [comment]
Unfortunately, the app crashed while I was doing the following:

(...)

This is the stack trace:/app.js:217
           return this.error(error);
                       ^

TypeError: Cannot read property 'error' of null
    at /app.js:217:24
    at Nodemailer.<anonymous> (/node_modules/nodemailer/lib/nodemailer.js:319:26)
    at /node_modules/nodemailer/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:134:28
    at callback (/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:334:14)
    at SMTPConnection.<anonymous> (/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:345:20)
    at SMTPConnection._actionRCPT (/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:1047:20)
    at SMTPConnection.<anonymous> (/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:1021:18)
    at SMTPConnection._processResponse (/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:610:16)
    at SMTPConnection._onData (/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:437:10)
    at emitOne (events.js:116:13)

**Comment by jordenc** [comment]
New version 0.2.3 added to appstore (not approved yet), which will fix this error and show the errors on "test" button in settings page.

**Comment by michelkamp** [comment]
great ,thanks for your effort !

**Comment by LesPaul1962** [comment]
Same problem, test works, but sending in a flow not. I use the gmail server. I have also a doorbird and a foscam camera and their email functions are working well.

**Comment by jordenc** [comment]
> Same problem, test works, but sending in a flow not. I use the gmail server. I have also a doorbird and a foscam camera and their email functions are working well.

If you restart the app, does it work then?
